name = "my-remix-app"
compatibility_date = "2024-05-20"
pages_build_output_dir = "./build/client"

[site]
bucket = "./build/client"

[build]
command = "npm run build"

[env.production]
vars = { NODE_ENV = "production" }
